# Generated by Django 3.1 on 2020-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
