# Generated by Django 3.1 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='impressionism', max_length=254),
            preserve_default=False,
        ),
    ]
