# Generated by Django 3.1 on 2020-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200817_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
