# Generated by Django 3.1 on 2020-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200820_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
