# Generated by Django 3.1 on 2020-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200820_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(),
        ),
    ]
