# Generated by Django 3.1 on 2020-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200828_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
